# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1de18413d431b6c2dfe6c71e9eee0b8966b37d598424210a4777ed31a3fed400305143ac62639abc45bc7963d3f2015d75450825b80ad512084a12f8c7df25a8

test:
  secret_key_base: 02f8b1219feb5685a2f7ae9ba5e071e3719e783a3595292d3fb545055bd87d2977b09b7b846b4c66ce41f2a1156536cf54f2e73c9f4e866e4601f18c0f039ec0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
